apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  targetNamespace: traefik
  dependsOn:
    - name: metallb
    - name: coredns-external
  chart:
    spec:
      chart: traefik
      version: 10.14.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.50.245.51
