apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  targetNamespace: kube-system
  dependsOn:
    - name: metallb
  chart:
    spec:
      chart: traefik
      version: 10.14.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
