apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-ingressroutes
  namespace: flux-system
spec:
  interval: 1m00s
  dependsOn:
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/overlays/dev/traefik-ingressroutes/routes
  prune: true
