apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  releaseName: csi-driver-smb
  targetNamespace: kube-system
  chart:
    spec:
      chart: csi-driver-smb
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
      version: "1.5.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
