apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: flux-system
spec:
  releaseName: minecraft-bedrock
  targetNamespace: default
  chart:
    spec:
      chart: minecraft-bedrock
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    nameOverride: ''
    minecraftServer:
      eula: 'TRUE'
      version: '1.18.2.03'
      onlineMode: false
      serverName: 'Мурск Сервер'
