apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux-system
spec:
  releaseName: coredns
  targetNamespace: external-dns
  dependsOn:
    - name: etcd
  chart:
    spec:
      chart: coredns
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
      version: "1.16.7"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    isClusterService: false
    serviceType: LoadBalancer
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.50.245.50
    servers:
      - zones:
          - zone: muralovka.ru
            scheme: dns://
        port: 53
        plugins:
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: etcd
            configBlock: |-
              path /skydns
              endpoint http://etcd.external-dns.svc.cluster.local:2379
      - zones:
          - zone: .
            scheme: dns://
        port: 53
        plugins:
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: forward
            parameters: . tls://9.9.9.9 tls://149.112.112.112
            configBlock: |-
              tls_servername dns.quad9.net
              health_check 5s
          - name: cache
            parameters: 30
