apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: flux-system
spec:
  releaseName: etcd
  targetNamespace: external-dns
  chart:
    spec:
      chart: etcd
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "6.13.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    rbac:
      # FIXME: Configure proper authentication
      create: false
