apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: flux-system
spec:
  releaseName: etcd
  targetNamespace: external-dns
  chart:
    spec:
      chart: etcd
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "6.13.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    readinessProbe:
      # FIXME: reenable when https://github.com/bitnami/charts/issues/8233 fixed
      enabled: false
    persistence:
      enabled: false
    auth:
      # FIXME: reenable when https://github.com/kubernetes-sigs/external-dns/issues/2616 implemented
      rbac:
        create: false
        allowNoneAuthentication: true
    resources:
      requests:
        memory: 128Mi
        cpu: 128m
      limits:
        memory: 128Mi
        cpu: 128m
