apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  targetNamespace: kube-system
  dependsOn:
    - name: coredns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: "1.7.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
      valuesKey: external-dns-values.yaml
