apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coredns-release.yaml
  - etcd-release.yaml
  - external-dns-release.yaml

configMapGenerator:
  - name: external-dns-values
    namespace: flux-system
    files:
      - coredns-values.yaml
      - etcd-values.yaml
      - external-dns-values.yaml
