apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  targetNamespace: external-dns
  dependsOn:
    - name: coredns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: "1.7.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    provider: coredns
    env:
      - name: ETCD_URLS
        value: http://etcd.external-dns.svc.cluster.local:2379
