apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - sources
  - csi-driver-smb
  - metallb
  - external-dns
  - traefik

configurations:
  - kustomizeconfig.yaml
