apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m00s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/base/traefik/helm-release
  wait: true
  prune: true
