ingressClass:
  enabled: true
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: false
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
service:
  type: LoadBalancer
