apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: plugin-config-templates
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - authme.yml.j2
      - luckperms.yml.j2
