apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - csi-driver-smb/smbcreds.yaml
  - metallb/config.yaml
  - traefik-ingressroutes

patchesStrategicMerge:
  - csi-driver-smb/storageClassPatch.yaml
