apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - release.yaml

components:
  - ../components/common
  - ../components/plugins

configMapGenerator:
  - name: config-survival
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - paper.yml
      - spigot.yml
