apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-survival
  namespace: flux-system
spec:
  releaseName: survival
  targetNamespace: minecraft
  dependsOn:
    - name: minecraft-postgres
  chart:
    spec:
      chart: minecraft
      version: 3.8.3
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
  interval: 10m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  values:
    minecraftServer:
      eula: TRUE
      version: 1.18.2
      type: PAPER
      overrideServerProperties: true
      onlineMode: false
      gameMode: survival
      memory: 4096M

    resources:
      requests:
        memory: 4096Mi
        cpu: 1
      limits:
        memory: 4096Mi
        cpu: 1

    securityContext:
      runAsUser: 1000
      fsGroup: 1000

    persistence:
      dataDir:
        enabled: true

    extraVolumes:
      - volumeMounts:
          - name: config
            mountPath: /server/paper.yml
            subPath: paper.yml
        volumes:
          - name: config
            configMap:
              name: config-survival
          - name: common-secrets
            secret:
              secretName: common-secrets

    initContainers:
      - name: cp-spigot-config
        image: busybox
        command: ['sh', '-c', 'cp /config/spigot.yml /server/spigot.yml']
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
          - name: datadir
            mountPath: /server
          - name: config
            mountPath: /config/spigot.yml
            subPath: spigot.yml
