apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  releaseName: home-assistant
  targetNamespace: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    initContainers:
      populate-config-dir:
        image: busybox
        command: 
          - sh
          - -c
          - |-
            for conf in groups automations scripts scenes; do
              touch -a /config/$conf.yaml
            done
        volumeMounts:
          - name: config
            mountPath: /config
    persistence:
      config:
        enabled: true
        storageClass: smb
      main-config:
        enabled: true
        type: configMap
        name: home-assistant-configmap
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
    env:
      TZ: Europe/Moscow
    hostNetwork: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: hassio.muralovka.ru
            paths:
              - path: /
