apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  releaseName: home-assistant
  targetNamespace: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: home-assistant-values
