apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-configmap
  namespace: home-assistant
data:
  configuration.yaml: |-
    default_config:

    tts:
      - platform: google_translate

    http:
      server_host: 0.0.0.0
      ip_ban_enabled: true
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        # FIXME: Restrict to node IPs instead of whole range of LANs
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16

    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
