apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  targetNamespace: traefik
  dependsOn:
    - metallb
  chart:
    spec:
      chart: traefik
      version: 10.14.1
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
