apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.100-192.168.1.110
