apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.50.245.50-10.50.245.100
