apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-release.yaml
  - proxy
  - lobby
  - survival

configMapGenerator:
  - name: plugin-config-templates
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - ./components/plugins/authme.yml.tmpl
      - ./components/plugins/luckperms.yml.tmpl

secretGenerator:
  - name: common-secrets
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    literals:
      - postgres-username=postgres
      - postgres-password=minecraft
      - rcon-password=NotSoSecure
