apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-release.yaml
  - proxy-release.yaml
  - lobby-release.yaml
  - plugins-common-config

configMapGenerator:
  - name: proxy-values
    namespace: flux-system
    files:
      - values.yaml=proxy-values.yaml

  - name: proxy-config
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - proxy-config/geyser-config.yaml
      - proxy-config/skinrestorer.yaml
      - proxy-config/velocity.toml

  - name: lobby-values
    namespace: flux-system
    files:
      - values.yaml=lobby-values.yaml

  - name: lobby-config
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - lobby-config/paper.yml
      - lobby-config/spigot.yml

secretGenerator:
  - name: common-secrets
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    literals:
      - postgres_username=minecraft
      - postgres_password=minecraft
      - rcon_password=NotSoSecure
  
  - name: minecraft-postgres-creds
    namespace: flux-system
    literals:
      - username=minecraft
      - password=minecraft
