apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-release.yaml
  - proxy-release.yaml
  - lobby-release.yaml
  - plugins-common-config

configMapGenerator:
  - name: proxy-values
    namespace: flux-system
    files:
      - values.yaml=proxy-values.yaml

  - name: proxy-config-templates
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - proxy-config/velocity.toml.j2

  - name: proxy-config
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - proxy-config/geyser-config.yaml

  - name: lobby-values
    namespace: flux-system
    files:
      - values.yaml=lobby-values.yaml

  - name: lobby-config-templates
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    files:
      - lobby-config/paper.yml.j2
      - lobby-config/server.properties.j2

secretGenerator:
  - name: common-secrets
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    literals:
      - velocity_secret=NotSoSecure
      - postgres_username=minecraft
      - postgres_password=minecraft
  
  - name: minecraft-postgres-creds
    namespace: flux-system
    literals:
      - username=minecraft
      - password=minecraft
