apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-release.yaml
  - proxy
  - lobby

secretGenerator:
  - name: common-secrets
    namespace: minecraft
    options:
      disableNameSuffixHash: true
    literals:
      - postgres-username=postgres
      - postgres-password=minecraft
      - rcon-password=NotSoSecure
