apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-lobby
  namespace: flux-system
spec:
  releaseName: lobby
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft
      version: 3.8.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    securityContext:
      fsGroup: 1001
    minecraftServer:
      eula: TRUE
      version: 1.18.1
      type: PAPER
      gamemode: adventure
      onlineMode: false
    persistence:
      storageClass: smb
      dataDir:
        enabled: true
