apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-lobby
  namespace: flux-system
spec:
  releaseName: lobby
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft
      version: 3.8.3
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
  interval: 10m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: lobby-values
