minecraftServer:
  eula: TRUE
  version: 1.18.2
  type: PAPER
  overrideServerProperties: true
  onlineMode: false
  gamemode: adventure
  spigetResources:
    - 34315 # https://www.spigotmc.org/resources/vault.34315/
    - 28140 # https://www.spigotmc.org/resources/luckperms.28140/
    # FIXME: Enable when Spigot link is fixed
    #- 6269  # https://www.spigotmc.org/resources/authmereloaded.6269/
    - 1997  # https://www.spigotmc.org/resources/protocollib.1997/
    - 19254 # https://www.spigotmc.org/resources/viaversion.19254/
    - 27448 # https://www.spigotmc.org/resources/viabackwards.27448/
    # FIXME: Enable when Spigot link is fixed
    #- 14356 # https://www.spigotmc.org/resources/advanced-portals.14356/
    - 2124  # https://www.spigotmc.org/resources/skinsrestorer.2124/
  rcon:
    enabled: true
    existingSecret: common-secrets
    secretKey: rcon_password
  # https://docs.papermc.io/paper/aikars-flags
  jvmXXOpts: |-
    -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200
    -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
    -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M
    -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4
    -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90
    -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem
    -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs
    -Daikars.new.flags=true
  memory: 1024M

resources:
  requests:
    memory: 1024Mi
    cpu: 500m
  limits:
    memory: 1024Mi
    cpu: 500m

securityContext:
  fsGroup: 1001

persistence:
  dataDir:
    enabled: true

extraVolumes:
  - volumes:
      - name: config-templates
        configMap:
          name: lobby-config-templates
      - name: common-secrets
        secret:
          secretName: common-secrets
      - name: plugin-config-templates
        configMap:
          name: plugin-config-templates

initContainers:
  - name: mkdir-plugins
    image: busybox
    command:
      - sh
      - -c
      - |-
        for pluginName in LuckPerms AuthMe; do
          mkdir -p /server/plugins/$pluginName
        done
    volumeMounts:
      - name: datadir
        mountPath: /server

  # FIXME: Remove when Spigot link is fixed
  - name: download-authme-plugin
    image: mwendler/wget
    args:
      [
        "--no-check-certificate",
        "--output-document", "/server/plugins/AuthMe.jar",
        "https://github.com/AuthMe/AuthMeReloaded/releases/download/5.6.0-beta2/AuthMe-5.6.0-beta2.jar",
      ]
    volumeMounts:
      - name: datadir
        mountPath: /server

  # FIXME: Remove when Spigot link is fixed
  - name: download-advanced-portals-plugin
    image: mwendler/wget
    args:
      [
        "--no-check-certificate",
        "--output-document", "/server/plugins/Advanced-Portals.jar",
        "https://dev.bukkit.org/projects/advanced-portals/files/latest",
      ]
    volumeMounts:
      - name: datadir
        mountPath: /server

  - name: render-paper-config
    image: objectiflibre/jinja-init
    env:
      - name: JINJA_SRC_FILE
        value: /templates/paper.yml.j2
      - name: JINJA_DEST_FILE
        value: /server/paper.yml
    volumeMounts:
      - name: config-templates
        mountPath: /templates/paper.yml.j2
        subPath: paper.yml.j2
      - name: datadir
        mountPath: /server
      - name: common-secrets
        mountPath: /secrets
        readOnly: true

  - name: render-luckperms-config
    image: objectiflibre/jinja-init
    env:
      - name: JINJA_SRC_FILE
        value: /templates/luckperms.yml.j2
      - name: JINJA_DEST_FILE
        value: /server/plugins/LuckPerms/config.yml
    volumeMounts:
      - name: plugin-config-templates
        mountPath: /templates/luckperms.yml.j2
        subPath: luckperms.yml.j2
      - name: datadir
        mountPath: /server
      - name: common-secrets
        mountPath: /secrets
        readOnly: true

  - name: render-authme-config
    image: objectiflibre/jinja-init
    env:
      - name: JINJA_SRC_FILE
        value: /templates/authme.yml.j2
      - name: JINJA_DEST_FILE
        value: /server/plugins/AuthMe/config.yml
    volumeMounts:
      - name: plugin-config-templates
        mountPath: /templates/authme.yml.j2
        subPath: authme.yml.j2
      - name: datadir
        mountPath: /server
      - name: common-secrets
        mountPath: /secrets
        readOnly: true
