apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-postgres
  namespace: flux-system
spec:
  releaseName: postgres
  targetNamespace: minecraft
  chart:
    spec:
      chart: postgresql
      version: 11.1.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: minecraft-postgres-creds
      valuesKey: username
      targetPath: auth.username
    - kind: Secret
      name: minecraft-postgres-creds
      valuesKey: password
      targetPath: auth.password
