serviceAnnotations:
  external-dns.alpha.kubernetes.io/hostname: minecraft.muralovka.ru
  metallb.universe.tf/allow-shared-ip: minecraft-proxy

minecraftProxy:
  type: VELOCITY
  plugins:
    - https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/velocity/target/Geyser-Velocity.jar
    - https://dev.bukkit.org/projects/advanced-portals/files/latest
    - https://ci.lucko.me/job/LuckPerms/1417/artifact/velocity/build/libs/LuckPerms-Velocity-5.4.9.jar
  velocityVersion: 3.1.2-SNAPSHOT
  onlineMode: false
  serviceType: LoadBalancer
  extraPorts:
    - name: bedrock
      containerPort: 19132
      protocol: UDP
      service:
        enabled: true
        type: LoadBalancer
        port: 19132
        annotations:
          metallb.universe.tf/allow-shared-ip: minecraft-proxy
      ingress:
        enabled: false

extraVolumes:
  - volumeMounts:
      - name: config
        mountPath: /server/plugins/Geyser-Velocity/config.yml
        subPath: geyser-config.yaml
    volumes:
      - name: config
        configMap:
          name: proxy-config
      - name: config-templates
        configMap:
          name: proxy-config-templates
      - name: common-secrets
        secret:
          secretName: common-secrets

initContainers:
  - name: mkdir-plugins
    image: busybox
    command: ['sh', '-c', 'mkdir -p /server/plugins/Geyser-Velocity']
    volumeMounts:
      - name: datadir
        mountPath: /server
  - name: render-velocity-config
    image: objectiflibre/jinja-init
    env:
      - name: JINJA_SRC_FILE
        value: /templates/velocity.toml.j2
      - name: JINJA_DEST_FILE
        value: /server/velocity.toml
    volumeMounts:
      - name: config-templates
        mountPath: /templates/velocity.toml.j2
        subPath: velocity.toml.j2
      - name: datadir
        mountPath: /server
      - name: common-secrets
        mountPath: /secrets
        readOnly: true
