apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-configmap
  namespace: minecraft
data:
  geyser-config.yaml: |-
    bedrock:
      address: 0.0.0.0
      port: 19132
      clone-remote-port: false
      motd1: "Geyser"
      motd2: "Another Geyser server."
      server-name: "Мурск Сервер"
      compression-level: 6
      enable-proxy-protocol: false
      #proxy-protocol-whitelisted-ips: [ "127.0.0.1", "172.18.0.0/16" ]
    remote:
      address: auto
      port: 25565
      auth-type: offline
      allow-password-authentication: true
      use-proxy-protocol: false
      forward-hostname: false
    floodgate-key-file: key.pem
    command-suggestions: true
    passthrough-motd: true
    passthrough-protocol-name: false
    passthrough-player-counts: true
    legacy-ping-passthrough: false
    ping-passthrough-interval: 3
    forward-player-ping: false
    max-players: 10
    debug-mode: false
    allow-third-party-capes: true
    allow-third-party-ears: false
    show-cooldown: title
    show-coordinates: true
    disable-bedrock-scaffolding: false
    always-quick-change-armor: false
    emote-offhand-workaround: "emotes-and-offhand"
    default-locale: ru_ru
    cache-images: 0
    allow-custom-skulls: true
    add-non-bedrock-items: true
    above-bedrock-nether-building: false
    force-resource-packs: true
    xbox-achievements-enabled: false
    metrics:
      enabled: true
      uuid: 34941573-1ba2-4457-82b7-8bbde4492a7e
    scoreboard-packet-threshold: 20
    enable-proxy-connections: false
    mtu: 1400
    use-direct-connection: true
    config-version: 4

  velocity.toml: |-
    config-version = "1.0"
    bind = "0.0.0.0:25577"
    motd = "&#09add3Мурск Сервер"
    show-max-players = 10
    online-mode = false
    prevent-client-proxy-connections = false
    player-info-forwarding-mode = "modern"
    forwarding-secret = "NotSoSecret"
    announce-forge = false
    kick-existing-players = false
    ping-passthrough = "DISABLED"

    [servers]
    lobby = "lobby-minecraft.minecraft.svc.cluster.local:25565"
    survival = "survival-minecraft.minecraft.svc.cluster.local:25565"
    creative = "creative-minecraft.minecraft.svc.cluster.local:25565"
    try = [
      "lobby"
    ]

    [forced-hosts]

    [advanced]
    compression-threshold = 256
    compression-level = -1
    login-ratelimit = 3000
    connection-timeout = 5000
    read-timeout = 30000
    haproxy-protocol = false
    tcp-fast-open = false
    bungee-plugin-message-channel = true
    show-ping-requests = false
    failover-on-unexpected-server-disconnect = true
    announce-proxy-commands = true
    log-command-executions = false

    [messages]
    kick-prefix = "&cKicked from %s: "
    disconnect-prefix = "&cCan't connect to %s: "
    online-mode-only = "&cThis server only accepts connections from online-mode clients.\n\n&7Did you change your username? Sign out of Minecraft, sign back in, and try again."
    no-available-servers = "&cThere are no available servers."
    already-connected = "&cYou are already connected to this proxy!"
    moved-to-new-server-prefix = "&cThe server you were on kicked you: "
    generic-connection-error = "&cAn internal error occurred in your connection."
