apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: flux-system
spec:
  releaseName: velocity
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
  interval: 10m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: proxy-values
