# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = 'generic/debian11'

K3S_MASTERS = 1
K3S_WORKERS = 2

NETWORK_PREFIX = '10.50.245.'
NETWORK_PAD = 10

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true

  (1..K3S_WORKERS).each do |node_id|
    config.vm.define "k3s_worker_#{node_id}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.hostname = "k3s-worker-#{node_id}"

      node.vm.network :private_network,
        :ip => "#{NETWORK_PREFIX}#{NETWORK_PAD + K3S_MASTERS + node_id}",
        :libvirt__forward_mode => 'route'

      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 1
        libvirt.memory = 1024
      end
    end
  end

  (1..K3S_MASTERS).each do |node_id|
    config.vm.define "k3s_master_#{node_id}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.hostname = "k3s-master-#{node_id}"

      node.vm.network :private_network,
        :ip => "#{NETWORK_PREFIX}#{NETWORK_PAD + node_id}",
        :libvirt__forward_mode => 'route'

      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2048
      end

      # Make Vagrant think it provisions only 1 node
      if node_id == K3S_MASTERS then
        node.vm.provision :ansible do |ansible|
          ansible.playbook = 'site.yaml'
          # Actually provision all nodes
          ansible.limit = 'all'
          ansible.galaxy_role_file = './roles/requirements.yaml'
          ansible.galaxy_roles_path = './.galaxy/roles'
          ansible.groups = {
            'k3s_masters' => ["k3s_master_[1:#{K3S_MASTERS}]"],
            'k3s_workers' => ["k3s_worker_[1:#{K3S_WORKERS}]"],
            'k3s:children' => ['k3s_masters', 'k3s_workers'],
          }
        end
      end
    end
  end
end
